- hosts: webservers
  become: true
  vars:
    pip_install_packages:
      - name: docker
    datadog_api_key: "{{ dd_api_key }}"
    datadog_checks:
      http:
        init_config:
        instances:
          - name: Website
            url: "{{ site_url }}"
    datadog_site: datadoghq.eu

  roles:
    - geerlingguy.pip
    - { role: datadog.datadog, become: yes }

  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: install

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      tags: install

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      tags: install

    - name: Install redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine
        ports:
          - 80:3000
        env:
          REDMINE_DB_POSTGRES: "{{ db_host }}"
          REDMINE_DB_PORT: "{{ db_port }}"
          REDMINE_DB_DATABASE: "{{ db_name }}"
          REDMINE_DB_USERNAME: "{{ db_username }}"
          REDMINE_DB_PASSWORD: "{{ db_password }}"
      tags: deploy
