db_host: db-postgresql-fra1-31055-do-user-15566484-0.c.db.ondigitalocean.com
db_port: "25060"
db_name: defaultdb
db_username: doadmin
db_password: "{{ vault_db_password }}"
dd_api_key: "{{ vault_dd_api_key }}"
app_url: http://kubryakov.online/
app_port: "80"
