db_host: rc1a-u1dcha05zz63ziqy.mdb.yandexcloud.net
db_port: "6432"
db_name: db
db_username: kirillku
db_password: "{{ vault_db_password }}"
dd_api_key: "{{ vault_dd_api_key }}"
app_url: http://kubryakov.online/
app_port: "80"
