db_host: db-postgresql-fra1-31055-do-user-15566484-0.c.db.ondigitalocean.com
db_port: "25060"
db_name: defaultdb
db_username: doadmin
db_password: "{{ vault_db_password }}"
app_url: http://kubryakov.online/
app_port: "80"
pip_install_packages:
  - name: docker
datadog_api_key: "{{ vault_dd_api_key }}"
datadog_checks:
  http:
    init_config:
    instances:
      - name: Website
        url: "{{ app_url }}"
datadog_site: datadoghq.eu
